### ISSUE TITLE
Phone screen contact screen animation

### ISSUE THREAD

**Issue by Sofiyana-1811** [bedanta12/my-portfolio#26]
In the phone screen, the contact screen is not fixed, its still the desktop page. 
Change the design and make the animation.
Refer the figma file and image below.
![iPhone 14 Pro - 6](https://github.com/bedanta12/my-portfolio/assets/69445987/b5ebe0ce-092f-4da2-b4ac-2f46baf7b690)
![iPhone 14 Pro - 8](https://github.com/bedanta12/my-portfolio/assets/69445987/f0cd1ef8-1dec-443b-bfc4-9c1bc27c054e)

**Comment by Sofiyana-1811** [comment]
The component is already present in ContactPageSmall.js, please integrate it so that in smaller screens that component slides up, while the normal component slides up in larger screens.

**Comment by Dhruv127** [comment]
assign me

**Comment by Dhruv127** [comment]
done you can check ..
PR #29
